[features]
seeds = false
skip-lint = false
[programs.devnet]
funding_crowd = "8RDzRfUrfsLdWEnJLgGPPyiAmBxcykjNhMCEabUAAhQf"

[registry]
# url = "https://api.apr.dev"
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
